// AUTO-GENERATED by scripts/build-png-manifest.ts.
// DO NOT EDIT by hand — regenerate via `npm run sprites:manifest`.
// One entry per file in public/creatures/*.png.

import type { CreatureKind } from '../levels/levels';

export const PNG_KINDS: ReadonlySet<CreatureKind> = new Set<CreatureKind>([
  'aqua-spark' as CreatureKind,
  'bolt-bunny' as CreatureKind,
  'flame-cub' as CreatureKind,
  'leaf-pup' as CreatureKind,
  'pebble-pal' as CreatureKind,
  'puff-bird' as CreatureKind,
  'shroom-buddy' as CreatureKind,
  'star-fish' as CreatureKind,
]);

export const PNG_SPRITE: Readonly<Partial<Record<CreatureKind, string>>> = {
  'aqua-spark': '/creatures/aqua-spark.png',
  'bolt-bunny': '/creatures/bolt-bunny.png',
  'flame-cub': '/creatures/flame-cub.png',
  'leaf-pup': '/creatures/leaf-pup.png',
  'pebble-pal': '/creatures/pebble-pal.png',
  'puff-bird': '/creatures/puff-bird.png',
  'shroom-buddy': '/creatures/shroom-buddy.png',
  'star-fish': '/creatures/star-fish.png',
} as const;
