// Scene background — renders the AI-generated PNG backdrop generated by
// Higgsfield (Flux 2.0). PNGs live in /public/scenes/ keyed by level id.
//
// The previous v0 implementation rendered hand-painted SVGs by `scene` kind
// (forest / meadow / beach). v1 keeps that prop for backwards compatibility
// — there's a 1:1 mapping kind → URL — but the actual visual is now the
// AI image. The SVG renderer is gone; if you need the old fallback, restore
// from git history (commit before v1-scene wiring).

import type { SceneKind } from '../levels/levels';

const SCENE_BY_KIND: Record<SceneKind, string> = {
  forest: '/scenes/lvl-1-forest.png',
  meadow: '/scenes/lvl-2-meadow.png',
  beach:  '/scenes/lvl-3-shore.png',
};

export function SceneBackground({ scene }: { scene: SceneKind }) {
  const url = SCENE_BY_KIND[scene];
  return (
    <div className="absolute inset-0 overflow-hidden" aria-hidden>
      <img
        src={url}
        alt=""
        decoding="async"
        loading="eager"
        // object-cover so portrait/landscape iPad both crop sensibly to the
        // 16:9 source. The deep palette gives a graceful navy fallback while
        // the PNG decodes.
        className="absolute inset-0 h-full w-full object-cover bg-night-deep"
        // The composited scene already has its own atmospheric lighting baked
        // in. We only need a soft global dimmer + a vignette so the spotlight
        // sweep has enough darkness to "reveal" against. Less aggressive than
        // the v0 brightness:0.62 because the painted creatures themselves
        // need to read clearly within the spotlight beam.
        style={{ filter: 'brightness(0.55) saturate(1.04)' }}
      />
      {/* Stronger vignette than v0 to make the spotlight beam pop. */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            'radial-gradient(ellipse at center, rgba(5, 7, 20, 0) 28%, rgba(5, 7, 20, 0.70) 100%)',
        }}
      />
    </div>
  );
}
