// Scene background — renders the AI-generated PNG backdrop generated by
// Higgsfield (Flux 2.0). PNGs live in /public/scenes/ keyed by level id.
//
// The previous v0 implementation rendered hand-painted SVGs by `scene` kind
// (forest / meadow / beach). v1 keeps that prop for backwards compatibility
// — there's a 1:1 mapping kind → URL — but the actual visual is now the
// AI image. The SVG renderer is gone; if you need the old fallback, restore
// from git history (commit before v1-scene wiring).

import type { SceneKind } from '../levels/levels';

const SCENE_BY_KIND: Record<SceneKind, string> = {
  forest: '/scenes/lvl-1-forest.png',
  meadow: '/scenes/lvl-2-meadow.png',
  beach:  '/scenes/lvl-3-shore.png',
};

export function SceneBackground({ scene }: { scene: SceneKind }) {
  const url = SCENE_BY_KIND[scene];
  return (
    <div className="absolute inset-0 overflow-hidden" aria-hidden>
      <img
        src={url}
        alt=""
        decoding="async"
        loading="eager"
        // object-cover so portrait/landscape iPad both crop sensibly to the
        // 16:9 source. The deep palette gives a graceful navy fallback while
        // the PNG decodes.
        className="absolute inset-0 h-full w-full object-cover bg-night-deep"
        style={{ filter: 'brightness(0.62) saturate(1.08)' }}
      />
      {/* Subtle vignette so the spotlight beam reads as the only light source.
          Tuned by hand — too dark and the AI detail disappears, too light and
          the searchlight effect goes flat. */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            'radial-gradient(ellipse at center, rgba(5, 7, 20, 0) 35%, rgba(5, 7, 20, 0.55) 100%)',
        }}
      />
    </div>
  );
}
