/**
 * Scan public/creatures/*.png and emit src/creatures/png-manifest.ts so the
 * Creature component knows which kinds have a generated PNG sprite (vs. need
 * to fall back to SvgCreature). The manifest is committed to the repo — it's
 * the source of truth for "PNG exists for this kind" at compile time.
 *
 * Run after generating new sprites: npm run sprites:manifest
 * Also runs as part of `npm run sprites:generate` and `npm run sprites:process`.
 */
import { readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO = path.resolve(__dirname, '..')
const PNG_DIR = path.join(REPO, 'public', 'creatures')
const OUT = path.join(REPO, 'src', 'creatures', 'png-manifest.ts')

async function main() {
  const entries = (await readdir(PNG_DIR)).filter((f) => f.endsWith('.png'))
  const kinds = entries.map((f) => f.replace(/\.png$/, '')).sort()
  const lines = [
    '// AUTO-GENERATED by scripts/build-png-manifest.ts.',
    '// DO NOT EDIT by hand — regenerate via `npm run sprites:manifest`.',
    '// One entry per file in public/creatures/*.png.',
    '',
    "import type { CreatureKind } from '../levels/levels';",
    '',
    'export const PNG_KINDS: ReadonlySet<CreatureKind> = new Set<CreatureKind>([',
    ...kinds.map((k) => `  '${k}' as CreatureKind,`),
    ']);',
    '',
    'export const PNG_SPRITE: Readonly<Partial<Record<CreatureKind, string>>> = {',
    ...kinds.map((k) => `  '${k}': '/creatures/${k}.png',`),
    '} as const;',
    '',
  ]
  await writeFile(OUT, lines.join('\n'))
  console.log(`✓ wrote ${path.relative(REPO, OUT)} (${kinds.length} PNG sprites)`)
}

main().catch((e) => { console.error(e); process.exit(1) })
