// Scene loader — maps a level id to its background image URL and triggers
// browser preloading. The PNGs were generated by Higgsfield / Flux 2.0 (see
// docs/higgsfield-mcp.md) and live in /public/scenes/, so Vite copies them
// into the build verbatim and the service worker caches them for offline.
//
// FUTURE EXTENSION (v1):
//   When the real /api/scene endpoint ships:
//     * Replace the static map with `fetch('/api/scene?level=...')`.
//     * Response body:
//         { id, title, scene_url, creatures: [{ id, kind, x, y, w, h, name }, ...] }
//     * Scenes can then be re-generated server-side per request (parent
//       picks a season/theme), and player-uploaded character avatars (see
//       docs/v1-character-prompt.md) get composited in.
//     * The service worker (public/sw.js) keeps stale-while-revalidate on
//       /api/scene/* so cached scenes load instantly on second visit.

import type { Level } from './levels/levels';
import { LEVELS, getLevel, nextLevelId } from './levels/levels';

/** Map level id → CDN-style URL for the AI-generated scene background.
 *  Order matters: keep aligned with src/levels/levels.ts ids. */
const SCENE_URL: Record<string, string> = {
  'lvl-1': '/scenes/lvl-1-forest.png',
  'lvl-2': '/scenes/lvl-2-meadow.png',
  'lvl-3': '/scenes/lvl-3-shore.png',
};

export function sceneUrl(levelId: string): string | undefined {
  return SCENE_URL[levelId];
}

export interface ScenePayload {
  level: Level;
  scene_url: string;
}

export async function loadScene(levelId: string): Promise<ScenePayload> {
  const level = getLevel(levelId) ?? LEVELS[0];
  const url = SCENE_URL[level.id] ?? SCENE_URL[LEVELS[0].id];
  // Wait for the actual image to decode so the play surface is never
  // shown empty. Cheaper than a setTimeout fudge and meets PRD §Performance.
  await new Promise<void>((resolve) => {
    const img = new Image();
    img.onload = () => resolve();
    img.onerror = () => resolve();
    img.src = url;
  });
  return { level, scene_url: url };
}

/** Prefetch the next level's scene so it's already in cache when the
 *  player taps "Next level →". Implemented as a hidden Image() so the
 *  browser cache + service worker both fill. */
export function prefetchScene(levelId: string): void {
  const next = nextLevelId(levelId);
  if (!next) return;
  const url = SCENE_URL[next];
  if (!url) return;
  const img = new Image();
  img.src = url;
}
