// Scene loader — front-end side of the AI image-generation pipeline
// described in PRD §Backend. v0 returns a synthetic "scene fetched"
// promise pointing at the bundled SVG renderer. The interface is the
// shape the real backend will expose.
//
// FUTURE EXTENSION:
//   When the real /api/scene endpoint ships:
//     * Replace the synthetic delay with `fetch('/api/scene?level=...')`.
//     * The response body becomes:
//         { id, title, scene_url, creatures: [{ id, kind, x, y, w, h, name }, ...] }
//     * `scene_url` points at a CDN-cached WebP or PNG generated by
//       GPT-Image / SD.
//     * The service worker (public/sw.js) already has a
//       stale-while-revalidate strategy keyed on `/api/scene/*` so
//       cached scenes load instantly on the second visit.
//
// PRD §Caching specifies:
//   * HTTP Cache-Control + ETag + Expires headers from the backend.
//   * Service worker for offline.
//   * <link rel="prefetch"> for the next level's scene.
// All three hooks are present in the system; only the backend stub
// remains to be replaced with real generation.

import type { Level } from './levels/levels';
import { LEVELS } from './levels/levels';

export interface ScenePayload {
  level: Level;
  /** When the real backend ships, this is the CDN URL of the scene. */
  scene_url?: string;
}

/** Stub: returns the bundled level definition with a tiny synthetic
 *  fetch delay so the loader UI gets a chance to display. */
export async function loadScene(levelId: string): Promise<ScenePayload> {
  // Network simulation — see PRD §Performance "load within 2s".
  await new Promise((r) => setTimeout(r, 200));
  const level = LEVELS.find((l) => l.id === levelId) ?? LEVELS[0];
  return { level };
}

/** Prefetch the NEXT scene in the background. v0 is a no-op (data is
 *  bundled). When the real backend ships, this should issue a
 *  `<link rel="prefetch">` for the next scene URL — see PRD. */
export function prefetchScene(levelId: string): void {
  void levelId;
  // intentionally empty in v0
}
